# SEO tag info
title: The Comfy Seat
description: The chair I sit in to geek out
url: https://genebean.github.io
baseurl: /jekyll-beanbag
twitter:
  username: technicalissues
  card: summary
logo: '/assets/images/Front-Row.png'
lang: en_US

# other info
email: gene@technicalissues.us
repository: 'genebean/jekyll-beanbag'
twitter_username: technicalissues
github_username: genebean
search: true

# Build settings
show_drafts: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  # style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Eastern # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

header:
  links:
    - label: 'GitHub'
      url: 'https://github.com/genebean'
    - label: 'Vagrant Boxes'
      url: 'https://app.vagrantup.com/genebean'

footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/genebean'
      username: 'genebean'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/technicalissues'
      username: 'technicalissues'
    - label: 'Vagrant Boxes'
      icon: 'fas fa-fw fa-link'
      url: 'https://app.vagrantup.com/genebean'
  tagline:
    pre-link: 'resides at'
    label: 'Linode'
    url: 'https://www.linode.com/?r=bf96f91b25091ab6d46a6433160cdd112fe5f73c'

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      short_name: "gene"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author: "gene"
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
