theme: 'minimal-mistakes-jekyll'
# minimal_mistakes_skin: 'default' # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: 'air' # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

site:
  locale: 'en-US'
  description: 'The chair I sit in to geek out'
  og_image: '/assets/images/Front-Row.png'
title: 'The Comfy Seat'
title_separator: '|'
subtitle: 'The chair I sit in to geek out'
name: 'Gene Liverman'
url: 'https://beanbag.technicalissues.us'
repository: 'genebean/jekyll-beanbag'
# teaser: /assets/images/500x300.png
logo: '/assets/images/Front-Row.png'
breadcrumbs: true
search: true
search_provider: 'algolia'
algolia:
  application_id: 'C1C47VIEU8'
  index_name: 'beanbag'
  search_only_api_key: '903d3424ebc0f0053aa0ec4e5c45b985'
  powered_by: true # true (default), false
twitter:
  username: technicalissues
  card: summary
author: gene
include:
  - _pages
exclude:
  - .dependabot/
  - azure-pipelines.yml
  - LICENSE
  - node_modules
  - README.md
  - scripts/
  - Vagrantfile
  - vendor/
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Eastern # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    year: '/archives/:year/'
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      author_profile: true
      layout: 'single'
      classes: wide
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      classes: wide
      author_profile: true
