baseURL = 'https://beanbag.technicalissues.us/'
languageCode = 'en-us'
title = 'The Comfy Seat'
paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    tabWidth = 4

[params]
  description = 'The chair I sit in to geek out'
  email = 'gene@technicalissues.us'
  logo = '/assets/images/Front-Row.png'
  author = 'gene'

[params.mastodon]
  instance = 'fosstodon.org'
  username = 'genebean'

[params.footer.tagline]
  preLink = 'resides at'
  label = 'Linode'
  url = 'https://www.linode.com/?r=bf96f91b25091ab6d46a6433160cdd112fe5f73c'

[[params.header.links]]
  label = 'GitHub'
  url = 'https://github.com/genebean'

[[params.header.links]]
  label = 'Vagrant Boxes'
  url = 'https://app.vagrantup.com/genebean'

[[params.footer.links]]
  label = 'GitHub'
  url = 'https://github.com/genebean'
  username = 'genebean'

[[params.footer.links]]
  label = 'Mastodon'
  url = 'https://fosstodon.org/@genebean'
  username = 'genebean'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'
    authors = '/authors/:slug/'
