[build]
publish = "_site"
command = "jekyll build"

[context.production.environment]
JEKYLL_ENV = "production"

[context.split1]
command = "jekyll build"

[context.split1.environment]
JEKYLL_ENV = "production"

[context.deploy-preview]
command = "jekyll build  --drafts"

[context.branch-deploy]
command = "jekyll build"

[[headers]]
  for = "/*"

  [headers.values]
   Strict-Transport-Security = "max-age=16070400; includeSubDomains; preload"
   X-Frame-Options = "DENY"
