[build]
publish = "public"
command = "npm ci && hugo --minify"

[build.environment]
HUGO_VERSION = "0.152.2"
HUGO_EXTENDED = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm ci && hugo --minify --buildDrafts --buildFuture"

[context.branch-deploy]
command = "npm ci && hugo --minify --buildDrafts --buildFuture"

[[headers]]
  for = "/*"

  [headers.values]
   Strict-Transport-Security = "max-age=16070400; includeSubDomains; preload"
   X-Frame-Options = "DENY"

[[redirects]]
  from = "/js/script.outbound-links.js"
  to = "https://stats.technicalissues.us/js/script.outbound-links.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://stats.technicalissues.us/api/event"
  status = 200
