[build]
publish = "public"
command = "curl -fsSL https://github.com/sass/dart-sass/releases/download/1.94.2/dart-sass-1.94.2-linux-x64.tar.gz | tar xz -C /tmp && PATH=$PATH:/tmp/dart-sass hugo --minify"

[build.environment]
HUGO_VERSION = "0.161.1"
HUGO_EXTENDED = "true"
DART_SASS_VERSION = "1.94.2"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "curl -fsSL https://github.com/sass/dart-sass/releases/download/1.94.2/dart-sass-1.94.2-linux-x64.tar.gz | tar xz -C /tmp && PATH=$PATH:/tmp/dart-sass hugo --minify --buildDrafts --buildFuture"

[context.branch-deploy]
command = "curl -fsSL https://github.com/sass/dart-sass/releases/download/1.94.2/dart-sass-1.94.2-linux-x64.tar.gz | tar xz -C /tmp && PATH=$PATH:/tmp/dart-sass hugo --minify --buildDrafts --buildFuture"

[[headers]]
  for = "/*"

  [headers.values]
   Strict-Transport-Security = "max-age=16070400; includeSubDomains; preload"
   X-Frame-Options = "DENY"

[[redirects]]
  from = "/js/script.outbound-links.js"
  to = "https://stats.technicalissues.us/js/script.outbound-links.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://stats.technicalissues.us/api/event"
  status = 200
